DESCRIPTION = "Libretro Nintendo GameCube cores"

inherit retro-packagegroup

LIBRETRO_NGC_CORES_ARCH_SPECIFIC = ""
LIBRETRO_NGC_CORES_ARCH_SPECIFIC_64bit += "dolphin-libretro"

LIBRETRO_NGC_CORES ?= "${LIBRETRO_NGC_CORES_ARCH_SPECIFIC}"

RRECOMMENDS_${PN} = "${LIBRETRO_NGC_CORES}"
