inherit libretro

LIBRETRO_GIT_PROTOCOL ?= ";protocol=https"
LIBRETRO_GIT_FETCHER ?= "gitsm://"

S = "${WORKDIR}/git"
SRC_URI = "${LIBRETRO_GIT_FETCHER}${LIBRETRO_REPO}${LIBRETRO_GIT_PROTOCOL}"
SRCREV ?= "${AUTOREV}"
