OVERRIDES_append_aarch64 = ":armarch:arm64"
OVERRIDES_append_aarch64_be = ":armarch:arm64"
OVERRIDES_append_arm = ":armarch:arm32"
OVERRIDES_append_armeb = ":armarch:arm32"
OVERRIDES_append_x86 = ":x86arch"
OVERRIDES_append_x86-64 = ":x86arch"
